name: ci

on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          cp .env.ci .env
          npm install
          npm run lint
          npm run build
